//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDEE
    {
        public ATTENDEE()
        {
            this.Attendings = new HashSet<Attending>();
            this.HospitalEmployees = new HashSet<HospitalEmployee>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Attending> Attendings { get; set; }
        public virtual ICollection<HospitalEmployee> HospitalEmployees { get; set; }
    }
}
