//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.HospitalEmployees = new HashSet<HospitalEmployee>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int DeptID { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<HospitalEmployee> HospitalEmployees { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
