//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int DrugID { get; set; }
        public string DrugName { get; set; }
        public string TakeAt { get; set; }
    
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
