//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalEmployee
    {
        public HospitalEmployee()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int EID { get; set; }
        public string EName { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> EmpTypeID { get; set; }
    
        public virtual ATTENDEE ATTENDEE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
