//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PID { get; set; }
        public System.DateTime PresDate { get; set; }
        public Nullable<int> PresByID { get; set; }
        public Nullable<int> DrugID { get; set; }
        public int Days { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual HospitalEmployee HospitalEmployee { get; set; }
    }
}
